# Generated by Django 4.1.2 on 2024-11-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, unique=True)),
                ('mobile_number', models.CharField(blank=True, default=None, max_length=10, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=10)),
                ('company_name', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=50)),
                ('vat_no', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Director', 'Director'), ('Finance Manager', 'Finance Manager'), ('General Manager', 'General Manager')], max_length=50)),
                ('designation', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
