# Generated by Django 4.1.2 on 2024-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0002_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
