# Generated by Django 4.1.2 on 2024-11-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0004_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
